### PR TITLE
Avoid type name clash

### PR DESCRIPTION
**Pull request by yixuan**
Hello Will,

In preparing the new version of `RcppEigen`, I checked the dependent packages and found that `BigVAR` failed in the compilation. This is because in Eigen 3.3, there is a function `cube` defined in the namespace of Eigen. When using both namespaces as in `inst/include/BigVAR.h`, the `cube` type in `RcppExports.cpp` will have conflicting definitions.

This PR solves this by only exporting necessary type names in `inst/include/BigVAR.h`. Hope this could make our transition to Eigen 3.3 easier.

### CODE REVIEW

**Comment by wbnicholson** [comment]
Thank you for pointing this out, I will update the package on cran.

**Comment by yixuan** [comment]
Hi Will,
Would you please submit an updated version of BigVAR to CRAN so that we can then update RcppEigen without breaking existing reverse dependencies? Thank you.

**Comment by wbnicholson** [comment]
I just submitted the update to cran.

**Comment by yixuan** [comment]
Thank you!

**Pull request merged**
